replaceList = ['c++', 'spring', 'agile', 'salesforce', 'elastic', 'network', 'non it',
               'optimization', 'opthal', 'electric', 'ecommerce', 'dynamic', 'big data',
               'apparel', 'agile', 'sales', 'spark', 'node', 'test', 'angular', 'qa',
               'ghaphic', 'aws', 'python', 'unity', 'design', 'support', 'sql', 'soap',
               'rest', 'java', 'business development', 'analytics', 'mongo', 'oracle',
               'coding', 'frontend', 'soft skills', 'excel', 'sap', 'react', 'devops',
               'consultant', 'ios', 'j2ee', 'relationship', 'risk',
               'machine learning', 'market', 'mba', 'microservice', 'mobile', 'cloud',
               'event', 'fullstack', 'game', 'hr ', 'hybris', 'financ', 'digital', 'dns',
               'warehouse', 'structure', 'counsel', 'customer', 'programming', 'c#',
               'content', 'contract', 'manufacturing', 'education', 'cosmos', 'amazon', 'code', 'communication',
               'bootstrap', 'protocol', 'magento', 'lookup', 'advisor', 'developer', 'payroll', 'selenium',
               'calendar', 'algorithm', 'recruit', 'account', 'client', 'cisco', 'clinic', 'civil',
               'etl', 'bank', 'blog', 'hyper', 'bpo', 'call', 'application', 'asp', 'tech', 'b2b',
               'b2c', 'balance sheet', 'team', 'photo', 'predictive', 'pivot', 'placement', 'assistant', 'verification', 'fixed income', 'automation', 'avaya', 'acad', 'ad ',
               'agricultur', 'denial', 'french', 'terraform', 'trade', 'service engineer', 'front', 'stack', 'android', 'docker', 'apache', 'api', 'zoho', 'autocad', 'animation',
               'graphic', 'jenkin', 'regulatory', 'medical', 'kpi', 'reception', 'reconcil',
               'record', 'macro', 'payment', 'web serv',
               'ibm', '3d', 'voice', 'chat', 'iphone', 'app', 'incident', 'industry', 'html',
               'holiday', 'backend', 'hibernate', '.net', 'translation', 'admin', 'adobe',
               'quality', 'tele', 'microsoft', 'mechanical', 'ab initio', 'object oriented', 'document',
               'performance', 'js', 'script', 'software', 'zen',
               'spanish', 'healthcare', 'qlik', 'visualforce', 'mortgage', 'print', 'property',
               'threading', 'bengali', 'data analys', 'data model', 'dbms', 'windows', 'webservice', 'visual studio', 'russian',
               'japanese', 'cgi', 'micro service', 'orm', 'accountant', 'socket', 'privacy',
               'problem solving',
               'pharma', 'presentation', 'insurance', 'model', 'influx', 'brand', 'transaction',
               'operation', 'database',
               'research', 'hcm', 'loan', 'azure', 'business', 'budget', 'fintech', 'it ',
               'product', 'dagger', 'program', 'ruby', 'rail', 'finance', 'hana', 'shell',
               'soft skill', 'solution', 'oop']
